routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\ArticleController::class, 'index'])->name('main.index');

Auth::routes();

Route::resource('articles', 'App\Http\Controllers\ArticleController')->only(['show']);
Route::resource('comments', 'App\Http\Controllers\CommentController')->only(['store']);
// Route::get('/articles/{id}', [App\Http\Controllers\ArticleController::class, 'show'])->name('main.show');
// Route::post('/comments', [App\Http\Controllers\commentcontroller::class, 'store'])->name('comment.store');

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'isAdmin'],
    'as' => 'admin.'
    ], function () {

    /* Articles */
    
    Route::resource('articles', 'App\Http\Controllers\Admin\ArticleController');
    // Route::get('/articles', [App\Http\Controllers\Admin\ArticleController::class, 'index'])->name('admin.article.index');
    // Route::get('/articles/create', [App\Http\Controllers\Admin\ArticleController::class, 'create'])->name('admin.article.create');
    // Route::post('/articles/store', [App\Http\Controllers\Admin\ArticleController::class, 'store'])->name('admin.article.store');
    // Route::post('/articles/{id}', [App\Http\Controllers\Admin\ArticleController::class, 'update'])->name('admin.article.update');
    // Route::post('/articles/{id}/destroy', [App\Http\Controllers\Admin\ArticleController::class, 'destroy'])->name('admin.article.destroy');

    /* Comments */
    Route::resource('comments', 'App\Http\Controllers\Admin\CommentController');
    // Route::get('/comments', [App\Http\Controllers\Admin\CommentController::class, 'index'])->name('admin.comments.index');
    // Route::get('/comments/{id}', [App\Http\Controllers\Admin\CommentController::class, 'show'])->name('admin.comments.show');
    // Route::get('/comments/{id}/edit', [App\Http\Controllers\Admin\CommentController::class, 'edit'])->name('admin.comments.edit');
    // Route::post('/comments/{id}', [App\Http\Controllers\Admin\CommentController::class, 'update'])->name('admin.comments.update');
    // Route::post('/comments/{id}/destroy', [App\Http\Controllers\Admin\CommentController::class, 'destroy'])->name('admin.comments.destroy');

});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'text',
        'published',
        'article_id',
    ];

    /**
     * Получить новость к которой привязан комментарий
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function article()
    {
        return $this->belongsTo(Article::class);
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Получить страницу в Админке со всеми отзывами
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin.comments.index', ['comments' => Comment::orderBy('id', 'desc')->get()]);
    }

    /**
     * Получить страницу в Админке с отзывом
     * @param $id - отзыва
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($id)
    {
        return view('admin.comments.show', ['comment' => Comment::findOrFail($id)]);
    }

    /**
     * Получить страницу с редактированием отзыва
     * @param $id - отзыва
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        return view('admin.comments.edit', ['comment' => Comment::findOrFail($id)]);
    }

    /**
     * Обновление текста отзыва или обновление статуса
     * @param $id - отзыва
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request)
    {
        // Если есть text то мы меняем комментарий
       if($request->text) {
           $request->validate(['text' => 'required|min:2|max:5000|regex:/[а-яА-Яa-zA-Z0-9]+/',]);

           $comment = Comment::find($id);
           $comment->update($request->all());

           return redirect()->route('admin.comments.index')->with('message', 'Комментарий успешно изменён');
       }
        // Если текста не было, значит это была публикация
        $published = Comment::find($id);
        $published->update(['published' => 1]);

        return redirect()->route('admin.comments.index')->with('message', 'Комментарий успешно опубликован');
    }

    /**
     * Удаление отзыва
     * @param $id - отзыва
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        Comment::destroy($id);

        return redirect()->route('admin.comments.index')->with('message', 'Комментарий успешно удален');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Requests\StoreCommentRequest;

class CommentController extends Controller
{
    /**
     * Добавление комментария на странице
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreCommentRequest $request)
    {
        Comment::create($request->all());

        return redirect()->back()->with('message', 'Комментарий успешно создана. Пожалуйста подождите пока модерация одобрит вашу запись');
    }
}

resources/views/admin/comments/edit.blade.php
@extends('layouts.app')

@section('content')
@include('admin.comments.partial.form', ['comment' => $comment])
@endsection

resources/views/admin/comments/index.blade.php
@extends('layouts.app')

@section('content')
    @if(session('message'))
        <div class="alert alert-success" role="alert">
            {{ session('message') }}
        </div>
    @endif
    @foreach($comments as $comment)
        <div class="container">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Name: {{ $comment->name }}</h5>
                    <p class="card-text">{{ mb_substr($comment->text, 0, 150) }}...</p>
                    <p class="card-text"><a class="btn btn-link" href="{{ route('admin.comments.show', $comment->id) }}">Просмотреть полностью отзыв</a></p>
                    <p class="card-text"><small class="text-muted">{{ __('articles.articles_index_created_at') }}: {{ $comment->created_at }} | {{ $comment->published ? 'Опубликована' : 'Не опубликована' }}</small></p>
                </div>
            </div>
        </div>
    @endforeach

@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(session('message'))
            <div class="alert alert-success" role="alert">
                {{ session('message') }}
            </div>
        @endif
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ $comment->name }}</h5>
                <p class="card-text">{{ $comment->text }}</p>
                <p class="card-text"><small class="text-muted">{{ __('articles.articles_index_created_at') }}: {{ $comment->created_at }} | В новости:
                        <a href="{{ route('articles.show', $comment->article->id) }}">{{ $comment->article->title }}</a></small></p>
                @if(!$comment->published)
                    <form action="{{ route('admin.comments.update', $comment->id) }}" method="POST" style="display: inline-block">
                        @csrf
                        @method('PUT')
                        <button class="btn btn-primary mb-5">Опубликовать</button>
                    </form>
                @endif
                <a class="btn btn-info mb-5" href="{{ route('admin.comments.edit', $comment->id) }}">Редактировать</a>
                <form action="{{ route('admin.comments.destroy', $comment->id) }}" method="POST" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger mb-5">Удалить</button>
                </form>
            </div>
        </div>
    </div>
@endsection