routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\ArticleController::class, 'index'])->name('main.index');

Auth::routes();

Route::resource('articles', 'App\Http\Controllers\ArticleController')->only(['show']);
Route::resource('comments', 'App\Http\Controllers\CommentController')->only(['store']);
// Route::get('/articles/{id}', [App\Http\Controllers\ArticleController::class, 'show'])->name('main.show');
// Route::post('/comments', [App\Http\Controllers\commentcontroller::class, 'store'])->name('comment.store');

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'isAdmin'],
    'as' => 'admin.'
    ], function () {

    /* Articles */
    
    Route::resource('articles', 'App\Http\Controllers\Admin\ArticleController');
    // Route::get('/articles', [App\Http\Controllers\Admin\ArticleController::class, 'index'])->name('admin.article.index');
    // Route::get('/articles/create', [App\Http\Controllers\Admin\ArticleController::class, 'create'])->name('admin.article.create');
    // Route::post('/articles/store', [App\Http\Controllers\Admin\ArticleController::class, 'store'])->name('admin.article.store');
    // Route::post('/articles/{id}', [App\Http\Controllers\Admin\ArticleController::class, 'update'])->name('admin.article.update');
    // Route::post('/articles/{id}/destroy', [App\Http\Controllers\Admin\ArticleController::class, 'destroy'])->name('admin.article.destroy');

    /* Comments */
    Route::resource('comments', 'App\Http\Controllers\Admin\CommentController');
    // Route::get('/comments', [App\Http\Controllers\Admin\CommentController::class, 'index'])->name('admin.comments.index');
    // Route::get('/comments/{id}', [App\Http\Controllers\Admin\CommentController::class, 'show'])->name('admin.comments.show');
    // Route::get('/comments/{id}/edit', [App\Http\Controllers\Admin\CommentController::class, 'edit'])->name('admin.comments.edit');
    // Route::post('/comments/{id}', [App\Http\Controllers\Admin\CommentController::class, 'update'])->name('admin.comments.update');
    // Route::post('/comments/{id}/destroy', [App\Http\Controllers\Admin\CommentController::class, 'destroy'])->name('admin.comments.destroy');

});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'text',
        'image',
        'published',
        'views',
    ];

    /**
     * Получение всех комментарие данной страницы
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\ArticleEvent;
use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\StoreArticleRequest;

class ArticleController extends Controller
{
    /**
     * Получение всех опубликованых и не опубликованых новостей
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin.articles.index', [
            'articlesAll' => Article::orderBy('published', 'asc')->get()
        ]);
    }

    /**
     * Страница создания новой новости
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('admin.articles.create');
    }

    /**
     * Создание новой новости
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreArticleRequest $request)
    {
        $path = $request->file('image') !== null ? $request->file('image')->store('articles') : null;
        $params = $request->all();
        $params['image'] = $path;

        Article::create($params);

        return redirect()->route('admin.articles.index')->with('message', 'Публикация успешно создана');
    }

    /**
     * Обновление статуса новости (Задачи не было обновлять новость!? )
     * @param $id - новости
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id, Request $request)
    {
        $article = Article::findOrFail($id);
        if($request->published == 1) {
            $article->update([
                'published' => $request->published
            ]);
        } elseif($request->published == 0) {
            $article->update([
                'published' => $request->published
            ]);
        } else {
            return redirect()->route('admin.articles.index')->with('message', 'Ошибка параметра');
        }
        

        return redirect()->route('admin.articles.index')->with('message', 'Публикация успешно опубликована');
    }

    /**
     * Удаление новости
     * @param $id - новости
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $image = Article::find($id)->image;

        if($image) {
            event(new ArticleEvent($image));
        };
        
        Article::destroy($id);

        return redirect()->route('admin.articles.index')->with('message', 'Публикация успешно удалена');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Получить все опубликованые новости
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('articles.index', [
            'articles' => Article::where('published', 1)
                ->orderBy('created_at', 'desc')
                ->orderBy('views', 'desc')
                ->paginate(3)
        ]);
    }

    /**
     * Страница с новостью
     * @param $id - новости
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show($id)
    {
        $article = Article::findOrFail($id);

        $comments = $article->comments()
            ->where('published', 1)
            ->orderBy('created_at', 'asc')
            ->paginate(1);

        // Если в данной сессии мы уже смотрели эту запись, то не добавлять больше просмотры
        if(!session("article_$article->id")) {
            $article->update(['views' => ++$article->views]);
            session(["article_$article->id" => 'viewed']);
        }

        return view('articles.show', [
            'article'  => $article,
            'comments' => $comments
        ]);
    }
}

resources/views/admin/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger" role="alert">
                {{ $error }}
            </div>
        @endforeach
    @endif
    <form action="{{ route('admin.articles.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <label for="exampleInputEmail1" class="form-label">{{ __('articles.articles_admin_create_1') }}</label>
            <input type="text" class="form-control" name="title" id="exampleInputEmail1" aria-describedby="emailHelp">

            <label for="exampleInputEmail1" class="form-label">{{ __('articles.articles_admin_create_2') }}</label>
            <input type="text" class="form-control" name="text" id="exampleInputEmail1" aria-describedby="emailHelp">

            <label for="formFile" class="form-label">{{ __('articles.articles_admin_create_3') }}</label>
            <input class="form-control" type="file" name="image" id="formFile">

{{--            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>--}}
            <input type="radio" class="form-check-input" name="published" value="1" id="exampleCheck1"><label class="form-check-label" for="exampleCheck1">Опубликовать</label><br>
            <input type="radio" class="form-check-input" name="published" value="0" id="exampleCheck2"><label class="form-check-label" for="exampleCheck2">Не опубликовать</label>
        <br>
{{--            <label class="form-check-label" for="exampleCheck1">Check me out</label>--}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(session('message'))
            <div class="alert alert-success" role="alert">
                {{ session('message') }}
            </div>
        @endif
        <a class="btn btn-primary mb-5" href="{{ route('admin.articles.create') }}">{{ __('articles.articles_admin_index_btn_add_news') }}</a>
        <a class="btn btn-primary mb-5" href="{{ route('admin.comments.index') }}">Гостевая книга</a>
        <div class="row">
            <h1>Все новости</h1>
            <hr>
        </div>
        <div class="row">
            @foreach($articlesAll as $article)
                <div class="card mb-4 col-md-4">
                    <strong>{{ $article->published ? 'Опубликована' : 'Не опубликована' }}</strong>
                    <img src="{{ Storage::url($article->image) }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{ route('articles.show', $article->id) }}">{{ $article->title }}</a></h5>
                        <p class="card-text">{{ $article->text }}</p>
                        <p class="card-text"><a class="btn btn-link" href="{{ route('articles.show', $article->id) }}">{{ __('articles.articles_index_link_readmore') }}</a></p>
                        <p class="card-text"><small class="text-muted">{{ __('articles.articles_index_created_at') }}: {{ $article->updated_at }} | {{ __('articles.articles_index_views') }}: {{ $article->views }}</small></p>
                        <div class="d-flex">
                            @if(!$article->published)
                            <form class="mr-2" action="{{ route('admin.articles.update', $article->id) }}" method="POST">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="published" value="1">
                                <button type="submit" class="btn btn-primary mb-5">{{ __('articles.articles_admin_index_btn_publish') }}</button>
                            </form>
                            @else
                            <form class="mr-2" action="{{ route('admin.articles.update', $article->id) }}" method="POST">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="published" value="0">
                                <button type="submit" class="btn btn-danger mb-5">снять с публикации</button>
                            </form>
                            @endif
                            <form action="{{ route('admin.articles.destroy', $article->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-primary mb-5">{{ __('articles.articles_admin_index_btn_delete') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection